spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity-in-milliseconds: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

app:
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      scope: "openid email profile"

    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      scope: "account_email profile_nickname"

    frontend-redirect-url: ${FRONTEND_REDIRECT_URI}

  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "https://api.sanidine.site/" # 나중에 환경변수로 빼주세요

auth:
  cookie:
    secure: false
    refresh-max-age: 604800
    same-site: Lax

springdoc:
  swagger-ui:
    path: /
