spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity-in-milliseconds: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

app:
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: https://api.sanidine.site/oauth2/callback/google
      scope: "openid email profile"

    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: https://api.sanidine.site/oauth2/callback/kakao
      scope: "account_email profile_nickname"

    frontend-redirect-url: https://www.naver.com # 임시

auth:
  cookie:
    secure: false # 운영 시 true로
    refresh-max-age: 604800

springdoc:
  swagger-ui:
    path: /
